var namespaceBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders =
[
    [ "KitchenOrderButtonsControl", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1KitchenOrderButtonsControl.html", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1KitchenOrderButtonsControl" ],
    [ "KitchenOrderGridControl", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1KitchenOrderGridControl.html", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1KitchenOrderGridControl" ],
    [ "OrderKanbanColumnControl", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1OrderKanbanColumnControl.html", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1OrderKanbanColumnControl" ],
    [ "TableBillSummaryControl", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1TableBillSummaryControl.html", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1TableBillSummaryControl" ],
    [ "TableOrderDetailsControl", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1TableOrderDetailsControl.html", "classBistroQ_1_1Presentation_1_1Views_1_1UserControls_1_1Orders_1_1TableOrderDetailsControl" ]
];